<a href="https://colab.research.google.com/github/nbisso/TP2-Orga-7506/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://www.analyticsvidhya.com/blog/2020/08/types-of-categorical-data-encoding/

In [ ]:
!pip install --upgrade category_encoders
import pandas as pd
import category_encoders as ce

Collecting category_encoders
  Downloading https://files.pythonhosted.org/packages/44/57/fcef41c248701ee62e8325026b90c432adea35555cbc870aff9cfba23727/category_encoders-2.2.2-py2.py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 5.8MB/s
Requirement already satisfied, skipping upgrade: statsmodels>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.10.2)
Requirement already satisfied, skipping upgrade: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.4.1)
Requirement already satisfied, skipping upgrade: numpy>=1.14.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.19.5)
Requirement already satisfied, skipping upgrade: pandas>=0.21.1 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (1.1.5)
Requirement already satisfied, skipping upgrade: patsy>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.5.1)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders) (0.22.2.post1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.1->category_encoders) (2018.9)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.7/dist-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.0.1)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.2.2

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train_labels = pd.read_csv('/content/drive/MyDrive/datasets_tp2/train_labels.csv')

In [ ]:
train_values = pd.read_csv('/content/drive/MyDrive/datasets_tp2/train_values.csv')

In [ ]:
df_test = pd.read_csv('/content/drive/MyDrive/datasets_tp2/test_values.csv')

In [ ]:
train_values.drop(['geo_level_2_id', 'geo_level_3_id'], axis = 1, inplace= True)

In [ ]:
df_test.drop(['geo_level_2_id', 'geo_level_3_id'], axis = 1, inplace= True)

In [ ]:
train_values['mud_stone_per_geo_level_1'] = train_values[['geo_level_1_id', 'has_superstructure_mud_mortar_stone']]\
.groupby('geo_level_1_id').transform('sum')

In [ ]:
train_values

        building_id  ...  mud_stone_per_geo_level_1
0            802906  ...                      18239
1             28830  ...                      17290
2             94947  ...                      14301
3            590882  ...                       5559
4            201944  ...                       3502
...             ...  ...                        ...
260596       688636  ...                       5028
260597       669485  ...                      20257
260598       602512  ...                      20257
260599       151409  ...                      10404
260600       747594  ...                      14301

[260601 rows x 38 columns]

In [ ]:
train_values['avg_floors_per_year'] = train_values[['age', 'count_floors_pre_eq']].groupby('age').transform('mean')

In [ ]:
train_values['avg_area'] = train_values[['geo_level_1_id', 'area_percentage']].\
groupby('geo_level_1_id').transform('mean')

## Binary Enconding

In [ ]:
df_test['mud_stone_per_geo_level_1'] = df_test[['geo_level_1_id', 'has_superstructure_mud_mortar_stone']]\
.groupby('geo_level_1_id').transform('sum')

In [ ]:
df_test['avg_floors_per_year'] = df_test[['age', 'count_floors_pre_eq']].groupby('age').transform('mean')

In [ ]:
df_test['avg_area'] = df_test[['geo_level_1_id', 'area_percentage']].\
groupby('geo_level_1_id').transform('mean')

In [ ]:
encoder= ce.BinaryEncoder(cols= ['land_surface_condition', 'foundation_type', \
                            'roof_type', 'ground_floor_type', 'other_floor_type', 'position', 'plan_configuration', 'legal_ownership_status'], return_df = True)

#### Aplico binary Encoding a set de entrenamiento

In [ ]:
df_binary_encoding = encoder.fit_transform(train_values)

/usr/local/lib/python3.7/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

In [ ]:
df_binary_encoding

        building_id  geo_level_1_id  ...  avg_floors_per_year  avg_area
0            802906               6  ...             2.253883  8.281859
1             28830               8  ...             2.020671  7.692767
2             94947              21  ...             2.020671  7.363490
3            590882              22  ...             2.020671  8.233525
4            201944              11  ...             2.253883  8.860706
...             ...             ...  ...                  ...       ...
260596       688636              25  ...             2.325627  7.717105
260597       669485              17  ...             1.844015  8.066978
260598       602512              17  ...             2.325627  8.066978
260599       151409              26  ...             2.020671  9.105196
260600       747594              21  ...             2.020671  7.363490

[260601 rows x 60 columns]

#### Aplico binary Encoding a set de test

In [ ]:
test_binary_encoding = encoder.fit_transform(df_test)

/usr/local/lib/python3.7/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

In [ ]:
test_binary_encoding

       building_id  geo_level_1_id  ...  avg_floors_per_year  avg_area
0           300051              17  ...             2.142413  8.118089
1            99355               6  ...             2.181873  8.288253
2           890251              22  ...             1.955587  8.207028
3           745817              26  ...             1.864924  9.106268
4           421793              17  ...             2.084135  8.118089
...            ...             ...  ...                  ...       ...
86863       310028               4  ...             2.399148  6.952799
86864       663567              10  ...             2.181873  6.734563
86865      1049160              22  ...             2.310330  8.207028
86866       442785               6  ...             1.955587  8.288253
86867       501372              26  ...             2.019947  9.106268

[86868 rows x 60 columns]

In [ ]:
test_binary_encoding.to_csv('/content/drive/MyDrive/datasets_tp2/test_binary.csv', index = False)

In [ ]:
df_binary_encoding.to_csv('/content/drive/MyDrive/datasets_tp2/train_binary.csv', index = False)

## Dummy Encoding

#### Aplico Dummy Encoding a set de entrenamiento

In [ ]:
df_dummy_encoding = pd.get_dummies(train_values, columns =['land_surface_condition', 'foundation_type', \
                            'roof_type', 'ground_floor_type', 'other_floor_type', 'position', 'plan_configuration', 'legal_ownership_status'])

In [ ]:
df_dummy_encoding

        building_id  ...  legal_ownership_status_w
0            802906  ...                         0
1             28830  ...                         0
2             94947  ...                         0
3            590882  ...                         0
4            201944  ...                         0
...             ...  ...                       ...
260596       688636  ...                         0
260597       669485  ...                         0
260598       602512  ...                         0
260599       151409  ...                         0
260600       747594  ...                         0

[260601 rows x 70 columns]

#### Aplico Dummy Encoding a set de test

In [ ]:
test_dummy_encoding = pd.get_dummies(df_test, columns =['land_surface_condition', 'foundation_type', \
                            'roof_type', 'ground_floor_type', 'other_floor_type', 'position', 'plan_configuration', 'legal_ownership_status'])

In [ ]:
test_dummy_encoding

       building_id  ...  legal_ownership_status_w
0           300051  ...                         0
1            99355  ...                         0
2           890251  ...                         0
3           745817  ...                         0
4           421793  ...                         0
...            ...  ...                       ...
86863       310028  ...                         1
86864       663567  ...                         0
86865      1049160  ...                         0
86866       442785  ...                         0
86867       501372  ...                         0

[86868 rows x 70 columns]

In [ ]:
#df_dummy_encoding.to_csv('/content/drive/MyDrive/datasets_tp2/train_values_dummy.csv', index = False)

In [ ]:
#test_dummy_encoding.to_csv('/content/drive/MyDrive/datasets_tp2/test_values_dummy.csv', index = False)